name: Demo Angular App

on:
  push:
    branches: [ master ]

jobs:
  build:
    name: Build app
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [ 12.x ]

    steps:
    - name: Checkout repo
      uses: actions/checkout@v2

    - name: Checkout E2E Tests repo
      uses: actions/checkout@v2
      with:
        repository: yash-kapila/demo-angular-app-e2e  # Temporary repo for e2e tests
        path: e2e-tests

    - name: Install Angular project dependencies
      uses: bahmutov/npm-install@v1

    # Spawn Angular dev server(port 4200)
    - name: Start server in the background
      run: npm start &

    - name: Execute E2E Tests
      uses: cypress-io/github-action@v2
      with:
        working-directory: e2e-tests
        browser: chrome

    - name: Capture screenshots artifacts
      uses: actions/upload-artifact@v2
      with:
        name: cypress-screenshots
        path: e2e-tests/cypress/screenshots

    - name: Capture video artifacts
      uses: actions/upload-artifact@v2
      if: always()
      with:
        name: cypress-videos
        path: e2e-tests/cypress/videos

    - name: Capture Mocha test report artifacts
      uses: actions/upload-artifact@v2
      if: always()
      with:
        name: test-report
        path: e2e-tests/mochawesome-report