name: Demo Angular App

on:
  push:
    branches: [ master ]

jobs:
  build:
    name: Build app
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v2

    - name: Use Node.js
      uses: actions/setup-node@v1
      with:
        node-version: 12.x

    - name: Checkout E2E repo
      uses: actions/checkout@v2
      with:
        repository: yash-kapila/demo-angular-app-e2e
        path: e2e-tests

    # Install Angular project dependencies
    - name: Install Angular project dependencies
      uses: bahmutov/npm-install@v1

    # Spawn Angular dev server(port 4200)
    - name: Start server in the background
      run: npm start &

    # Execute E2E Tests
    - name: Execute E2E Tests
      uses: cypress-io/github-action@v2
      with:
        working-directory: e2e-tests
        browser: chrome

    # Capture screenshots as artifacts
    - name: Capture screenshots artifacts
      uses: actions/upload-artifact@v2
      with:
        name: cypress-screenshots
        path: e2e-tests/cypress/screenshots

    # Capture videos as artifacts
    - name: Capture video artifacts
      uses: actions/upload-artifact@v2
      if: always()
      with:
        name: cypress-videos
        path: e2e-tests/cypress/videos